// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcX3_zR3KilzRG1pRVFR4xQ-EsqvJV6_0',
    appId: '1:629857021484:web:5243e58f9e54ebd73aab89',
    messagingSenderId: '629857021484',
    projectId: 'kajjafisioapp-e0cba',
    authDomain: 'kajjafisioapp-e0cba.firebaseapp.com',
    storageBucket: 'kajjafisioapp-e0cba.firebasestorage.app',
    measurementId: 'G-R0V33PMS5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_dlBvsexRCgkUm8tAuCJmYqPesWXgCw',
    appId: '1:629857021484:android:491ba5de6bab09a63aab89',
    messagingSenderId: '629857021484',
    projectId: 'kajjafisioapp-e0cba',
    storageBucket: 'kajjafisioapp-e0cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgWv7LW8d-EN8D0BOmefVbrx8fyghz7g',
    appId: '1:629857021484:ios:6344c23ea66747663aab89',
    messagingSenderId: '629857021484',
    projectId: 'kajjafisioapp-e0cba',
    storageBucket: 'kajjafisioapp-e0cba.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYgWv7LW8d-EN8D0BOmefVbrx8fyghz7g',
    appId: '1:629857021484:ios:6344c23ea66747663aab89',
    messagingSenderId: '629857021484',
    projectId: 'kajjafisioapp-e0cba',
    storageBucket: 'kajjafisioapp-e0cba.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcX3_zR3KilzRG1pRVFR4xQ-EsqvJV6_0',
    appId: '1:629857021484:web:e416e400dfd481c33aab89',
    messagingSenderId: '629857021484',
    projectId: 'kajjafisioapp-e0cba',
    authDomain: 'kajjafisioapp-e0cba.firebaseapp.com',
    storageBucket: 'kajjafisioapp-e0cba.firebasestorage.app',
    measurementId: 'G-BS5VWZ07L6',
  );

}